apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    app: myapp 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: ryuki999/app:latest